/* automatically generated by xdrgen from xdr/nav_msgs_OccupancyGrid.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/nav_msgs_OccupancyGrid.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCnav_msgs_OccupancyGrid_h
#define INCnav_msgs_OccupancyGrid_h



#include <ipc_bridge/msgs/roslib_Header.h>
#include <ipc_bridge/msgs/nav_msgs_MapMetaData.h>


struct nav_msgs_OccupancyGrid {
  roslib_Header header;
  nav_msgs_MapMetaData info;
  unsigned int data_length;
  char *data;
#define nav_msgs_OccupancyGrid_IPC_FORMAT "{" roslib_Header_IPC_FORMAT "," nav_msgs_MapMetaData_IPC_FORMAT ",uint,<char:3>}"
  static const char *getIPCFormat(void) {
    return nav_msgs_OccupancyGrid_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace nav_msgs
    {
        typedef nav_msgs_OccupancyGrid OccupancyGrid;
    }
}


#endif /* INCnav_msgs_OccupancyGrid_h */
