/* automatically generated by xdrgen from xdr/nav_msgs_GridCells.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/nav_msgs_GridCells.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCnav_msgs_GridCells_h
#define INCnav_msgs_GridCells_h



#include <ipc_bridge/msgs/roslib_Header.h>
#include <ipc_bridge/msgs/geometry_msgs_Point.h>


struct nav_msgs_GridCells {
  roslib_Header header;
  float cell_width;
  float cell_height;
  unsigned int cells_length;
  geometry_msgs_Point *cells;
#define nav_msgs_GridCells_IPC_FORMAT "{" roslib_Header_IPC_FORMAT ",float,float,uint,<" geometry_msgs_Point_IPC_FORMAT ":4>}"
  static const char *getIPCFormat(void) {
    return nav_msgs_GridCells_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace nav_msgs
    {
        typedef nav_msgs_GridCells GridCells;
    }
}


#endif /* INCnav_msgs_GridCells_h */
