/* automatically generated by xdrgen from xdr/nav_msgs_Path.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/nav_msgs_Path.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCnav_msgs_Path_h
#define INCnav_msgs_Path_h



#include <ipc_bridge/msgs/roslib_Header.h>
#include <ipc_bridge/msgs/geometry_msgs_PoseStamped.h>


struct nav_msgs_Path {
  roslib_Header header;
  unsigned int poses_length;
  geometry_msgs_PoseStamped *poses;
#define nav_msgs_Path_IPC_FORMAT "{" roslib_Header_IPC_FORMAT ",uint,<" geometry_msgs_PoseStamped_IPC_FORMAT ":2>}"
  static const char *getIPCFormat(void) {
    return nav_msgs_Path_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace nav_msgs
    {
        typedef nav_msgs_Path Path;
    }
}


#endif /* INCnav_msgs_Path_h */
