/* automatically generated by xdrgen from xdr/sensor_msgs_Imu.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/sensor_msgs_Imu.xdr last modified: Mon Jul  5 16:38:06 2010
 */

#ifndef INCsensor_msgs_Imu_h
#define INCsensor_msgs_Imu_h



#include <ipc_bridge/msgs/roslib_Header.h>
#include <ipc_bridge/msgs/geometry_msgs_Quaternion.h>
#include <ipc_bridge/msgs/geometry_msgs_Vector3.h>


struct sensor_msgs_Imu {
  roslib_Header header;
  geometry_msgs_Quaternion orientation;
  double orientation_covariance[9];
  geometry_msgs_Vector3 angular_velocity;
  double angular_velocity_covariance[9];
  geometry_msgs_Vector3 linear_acceleration;
  double linear_acceleration_covariance[9];
#define sensor_msgs_Imu_IPC_FORMAT "{" roslib_Header_IPC_FORMAT "," geometry_msgs_Quaternion_IPC_FORMAT ",[double:9]," geometry_msgs_Vector3_IPC_FORMAT ",[double:9]," geometry_msgs_Vector3_IPC_FORMAT ",[double:9]}"
  static const char *getIPCFormat(void) {
    return sensor_msgs_Imu_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace sensor_msgs
    {
        typedef sensor_msgs_Imu Imu;
    }
}


#endif /* INCsensor_msgs_Imu_h */
