/* automatically generated by xdrgen from xdr/geometry_msgs_PoseWithCovariance.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/geometry_msgs_PoseWithCovariance.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCgeometry_msgs_PoseWithCovariance_h
#define INCgeometry_msgs_PoseWithCovariance_h



#include <ipc_bridge/msgs/geometry_msgs_Pose.h>


struct geometry_msgs_PoseWithCovariance {
  geometry_msgs_Pose pose;
  float covariance[36];
#define geometry_msgs_PoseWithCovariance_IPC_FORMAT "{" geometry_msgs_Pose_IPC_FORMAT ",[float:36]}"
  static const char *getIPCFormat(void) {
    return geometry_msgs_PoseWithCovariance_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace geometry_msgs
    {
        typedef geometry_msgs_PoseWithCovariance PoseWithCovariance;
    }
}


#endif /* INCgeometry_msgs_PoseWithCovariance_h */
