/* automatically generated by xdrgen from xdr/geometry_msgs_Point32.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/geometry_msgs_Point32.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCgeometry_msgs_Point32_h
#define INCgeometry_msgs_Point32_h


struct geometry_msgs_Point32 {
  float x;
  float y;
  float z;
#define geometry_msgs_Point32_IPC_FORMAT "{float,float,float}"
  static const char *getIPCFormat(void) {
    return geometry_msgs_Point32_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace geometry_msgs
    {
        typedef geometry_msgs_Point32 Point32;
    }
}


#endif /* INCgeometry_msgs_Point32_h */
