/* automatically generated by xdrgen from xdr/geometry_msgs_Transform.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/geometry_msgs_Transform.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCgeometry_msgs_Transform_h
#define INCgeometry_msgs_Transform_h



#include <ipc_bridge/msgs/geometry_msgs_Quaternion.h>
#include <ipc_bridge/msgs/geometry_msgs_Vector3.h>


struct geometry_msgs_Transform {
  geometry_msgs_Vector3 translation;
  geometry_msgs_Quaternion rotation;
#define geometry_msgs_Transform_IPC_FORMAT "{" geometry_msgs_Vector3_IPC_FORMAT "," geometry_msgs_Quaternion_IPC_FORMAT "}"
  static const char *getIPCFormat(void) {
    return geometry_msgs_Transform_IPC_FORMAT;
  }


  geometry_msgs_Transform() {}
  geometry_msgs_Transform(const geometry_msgs_Transform& msg) :
    translation(msg.translation), rotation(msg.rotation)
  {
  }
  ~geometry_msgs_Transform()
  {
  }
  geometry_msgs_Transform& operator= (const geometry_msgs_Transform& msg)
  {
    translation = msg.translation;
    rotation = msg.rotation;

    return *this;
  }

};


namespace ipc_bridge
{
    namespace geometry_msgs
    {
        typedef geometry_msgs_Transform Transform;
    }
}


#endif /* INCgeometry_msgs_Transform_h */
