/* automatically generated by xdrgen from xdr/geometry_msgs_Quaternion.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/geometry_msgs_Quaternion.xdr last modified: Mon Jul  5 16:10:41 2010
 */

#ifndef INCgeometry_msgs_Quaternion_h
#define INCgeometry_msgs_Quaternion_h


struct geometry_msgs_Quaternion {
  double x;
  double y;
  double z;
  double w;
#define geometry_msgs_Quaternion_IPC_FORMAT "{double,double,double,double}"
  static const char *getIPCFormat(void) {
    return geometry_msgs_Quaternion_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace geometry_msgs
    {
        typedef geometry_msgs_Quaternion Quaternion;
    }
}


#endif /* INCgeometry_msgs_Quaternion_h */
