/* automatically generated by xdrgen from xdr/geometry_msgs_PoseWithCovarianceStamped.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/geometry_msgs_PoseWithCovarianceStamped.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCgeometry_msgs_PoseWithCovarianceStamped_h
#define INCgeometry_msgs_PoseWithCovarianceStamped_h



#include <ipc_bridge/msgs/roslib_Header.h>
#include <ipc_bridge/msgs/geometry_msgs_PoseWithCovariance.h>


struct geometry_msgs_PoseWithCovarianceStamped {
  roslib_Header header;
  geometry_msgs_PoseWithCovariance pose;
#define geometry_msgs_PoseWithCovarianceStamped_IPC_FORMAT "{" roslib_Header_IPC_FORMAT "," geometry_msgs_PoseWithCovariance_IPC_FORMAT "}"
  static const char *getIPCFormat(void) {
    return geometry_msgs_PoseWithCovarianceStamped_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace geometry_msgs
    {
        typedef geometry_msgs_PoseWithCovarianceStamped PoseWithCovarianceStamped;
    }
}


#endif /* INCgeometry_msgs_PoseWithCovarianceStamped_h */
