/* automatically generated by xdrgen from xdr/geometry_msgs_Pose.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/geometry_msgs_Pose.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCgeometry_msgs_Pose_h
#define INCgeometry_msgs_Pose_h



#include <ipc_bridge/msgs/geometry_msgs_Point.h>
#include <ipc_bridge/msgs/geometry_msgs_Quaternion.h>


struct geometry_msgs_Pose {
  geometry_msgs_Point position;
  geometry_msgs_Quaternion orientation;
#define geometry_msgs_Pose_IPC_FORMAT "{" geometry_msgs_Point_IPC_FORMAT "," geometry_msgs_Quaternion_IPC_FORMAT "}"
  static const char *getIPCFormat(void) {
    return geometry_msgs_Pose_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace geometry_msgs
    {
        typedef geometry_msgs_Pose Pose;
    }
}


#endif /* INCgeometry_msgs_Pose_h */
