/* automatically generated by xdrgen from xdr/geometry_msgs_TwistWithCovariance.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/geometry_msgs_TwistWithCovariance.xdr last modified: Wed Apr 28 10:56:47 2010
 */

#ifndef INCgeometry_msgs_TwistWithCovariance_h
#define INCgeometry_msgs_TwistWithCovariance_h



#include <ipc_bridge/msgs/geometry_msgs_Twist.h>


struct geometry_msgs_TwistWithCovariance {
  geometry_msgs_Twist twist;
  double covariance[36];
#define geometry_msgs_TwistWithCovariance_IPC_FORMAT "{" geometry_msgs_Twist_IPC_FORMAT ",[double:36]}"
  static const char *getIPCFormat(void) {
    return geometry_msgs_TwistWithCovariance_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace geometry_msgs
    {
        typedef geometry_msgs_TwistWithCovariance TwistWithCovariance;
    }
}


#endif /* INCgeometry_msgs_TwistWithCovariance_h */
