/* automatically generated by xdrgen from xdr/roslib_Header.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/roslib_Header.xdr last modified: Tue Jul  6 14:53:35 2010
 */

#ifndef INCroslib_Header_h
#define INCroslib_Header_h



#include <cstring>


struct roslib_Header {
  unsigned int seq;
  double stamp;
  char *frame_id;
#define roslib_Header_IPC_FORMAT "{uint,double,string}"
  static const char *getIPCFormat(void) {
    return roslib_Header_IPC_FORMAT;
  }


  roslib_Header() : seq(0), stamp(0) 
  {
    frame_id = new char[1];
    frame_id[0] = '\0';
  }
  roslib_Header(const roslib_Header& msg) :
    seq(msg.seq), stamp(msg.stamp)
  {
    frame_id = new char[strlen(msg.frame_id) + 1];
    strcpy(frame_id, msg.frame_id);
  }
  ~roslib_Header()
  {
    if (frame_id != 0)
      delete[] frame_id;
  }
  roslib_Header& operator= (const roslib_Header& msg)
  {
    seq = msg.seq;
    stamp = msg.stamp;

    if (frame_id != 0)
      delete[] frame_id;

    frame_id = new char[strlen(msg.frame_id) + 1];
    strcpy(frame_id, msg.frame_id);

    return *this;
  }

};


namespace ipc_bridge
{
    typedef roslib_Header Header;
}


#endif /* INCroslib_Header_h */
